### ISSUE TITLE
Не обрабатываются ошибки тестов, использующих утверждения BDD

### ISSUE THREAD

**Issue by theshadowco** [DoublesunRUS/ru.capralow.dt.unit.launcher#15]
При падении теста если используются утверждения BDD, то статус падения фиксируется, а лог не отображается. 

Пример

```
ЗаписанноеЗначение = "ТестоваяСтрока";

// нормально отработает
Фреймворк.ПроверитьТип(ЗаписанноеЗначение, Тип("ХранилищеЗначения");

// только статус, без текста
Фреймворк.Что(ЗаписанноеЗначение).ИмеетТип(Тип("ХранилищеЗначения");
```

**Comment by theshadowco** [comment]
Ошибка обнаружена в VA 
https://github.com/Pr-Mex/vanessa-automation/issues/412 

@DoublesunRUS 
Прошу закрыть ишузу после реализации указанной выше в VA

**Comment by DoublesunRUS** [comment]
Включено в версии 0.3.0
